AllCops:
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "vendor/**/*"
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 25
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
