version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
       - image: circleci/postgres:9.6.2-alpine
         environment:
           - POSTGRES_USER: turl
             POSTGRES_PASSWORD: sekret
             POSTGRES_DB: turl_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: rails test
